image: rust:1.36-stretch

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stages:
  - build

Build:
  stage: build
  before_script:
  - rustc --version
  - cargo --version
  script: make release

cache:
  paths:
    - cargo/
    - target/
