[package]
name = "luxtorpeda"
version = "0.1.0"
authors = ["Patryk Obara <dreamer.tan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdg = "^2.1"
users = "0.9"
psutil = "1.6.0"
